name: Test Base Image

on:
  push:
  workflow_dispatch:

jobs:
  test-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["noble", "jammy", "bookworm-slim"]
        dotnet-version: ["8.0", "9.0", "10.0"]
        exclude:
          - os: "jammy" # .NET 10.0 is not supported on Ubuntu 22.04
            dotnet-version: "10.0"
          - os: "bookworm-slim" # .NET 10.0 is not supported on debian bookworm
            dotnet-version: "10.0"
          - os: "bookworm-slim"
    env:
      BASE_IMAGE_TAG: abcpdf/mcr-aspnet:${{ matrix.dotnet-version }}-${{ matrix.os }}
      BASE_IMAGE_RC: abcpdf/mcr-aspnet:${{ matrix.dotnet-version }}-${{ matrix.os }}-${{ github.sha }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      ABCPDF_LICENSE_KEY: ${{ secrets.ABCPDF_LICENSE_KEY }}
    steps:
    - uses: actions/checkout@v5
    - name: Build Base Image
      run: |
        echo docker build -f ./Runtimes/mcr-aspnet-${{ matrix.os }}.Dockerfile -t  ${{ env.BASE_IMAGE_RC }} --build-arg DOTNET_VERSION=${{ matrix.dotnet-version }} .
        docker build -f ./Runtimes/mcr-aspnet-${{ matrix.os }}.Dockerfile -t  ${{ env.BASE_IMAGE_RC }} --build-arg DOTNET_VERSION=${{ matrix.dotnet-version }} .

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Build and Test
      working-directory: ./Testing/IntegrationTests
      run: | 
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build -verbosity detailed
     